"""Small model/simulation helpers shared by the BayesGBM tutorials."""

from __future__ import annotations

import numpy as np
from scipy.special import expit

from bayesgbm import GaussianPrior, Priors, StateModel


def sigmoid(z):
    return expit(z)


def binary_learning_model(*, fixed_alpha=False):
    """Two-option Rescorla-Wagner model with Bernoulli choices."""

    def evolution(x, theta, u_t, y_t):
        alpha = sigmoid(theta[0])
        x = x.copy()
        choice = int(y_t)
        reward = float(u_t["reward"])
        x[choice] += alpha * (reward - x[choice])
        return x

    def observation(x, phi, u_t):
        beta = np.exp(phi[0])
        return sigmoid(beta * (x[1] - x[0]))

    return StateModel(
        evolution=evolution,
        observation=observation,
        family="bernoulli",
        priors=Priors(GaussianPrior([0.0], [0.0 if fixed_alpha else 1.0], names=["alpha_raw"]), GaussianPrior([1.0], [1.0], names=["log_beta"])),
        initial_state=[0.5, 0.5],
        state_names=["Q0", "Q1"],
        name="two-option learning",
    )


def simulate_binary_subject(rng, n_trials=80, alpha=0.30, beta=3.0, block_length=20):
    q = np.array([0.5, 0.5])
    y = np.zeros(n_trials, dtype=int)
    reward = np.zeros(n_trials)
    for t in range(n_trials):
        # Reverse which option is better every block.
        if (t // block_length) % 2 == 0:
            reward_probability = np.array([0.75, 0.25])
        else:
            reward_probability = np.array([0.25, 0.75])
        # Choice generated by the same observation model used for fitting.
        p1 = sigmoid(beta * (q[1] - q[0]))
        choice = int(rng.random() < p1)
        # Generate reward from the current environmental contingency.
        r = float(rng.random() < reward_probability[choice])
        y[t] = choice
        reward[t] = r
        # Same Rescorla-Wagner update used in the fitted model.
        q[choice] += alpha * (r - q[choice])
    return {"y": y, "u": {"reward": reward}}


def continuous_model():
    """Deterministic one-state linear dynamics with Gaussian observations."""

    def evolution(x, theta, u_t, y_t):
        """Latent-state evolution."""
        gain = theta[0]
        return np.array([gain * x[0] + u_t])

    def observation(x, phi, u_t):
        """Gaussian observation mean."""
        offset = phi[0]
        return x[0] + offset

    def observation_covariance(phi, u_t):
        """Gaussian observation variance."""
        log_sigma = phi[1]
        sigma = np.exp(log_sigma)
        return sigma**2

    return StateModel(
        evolution=evolution,
        observation=observation,
        family="gaussian",
        priors=Priors(
            evolution=GaussianPrior(mean=[0.60], covariance=[0.50], names=["gain"]),
            observation=GaussianPrior(mean=[0.0, np.log(0.50)], covariance=[1.0, 1.0], names=["offset", "log_sigma"]),
        ),
        initial_state=[0.0],
        observation_covariance=observation_covariance,  # known residual variance for this tutorial
        state_names=["x"],
        name="continuous state model",
    )


def simulate_continuous_subject(rng, n_trials=60, gain=0.70, offset=0.0, sigma=0.50):
    """Simulate one continuous-outcome subject."""
    u = rng.normal(size=n_trials)
    x = 0.0
    y = np.zeros(n_trials)
    for t in range(n_trials):
        # Gaussian observation
        mean = x + offset
        y[t] = mean + rng.normal(0.0, sigma)
        # Deterministic latent-state evolution
        x = gain * x + u[t]
    return {"y": y, "u": u}


def filtered_continuous_model():
    """Linear-Gaussian hidden state with genuine internal state uncertainty."""

    def evolution(x, theta, u_t, y_t):
        return np.array([theta[0] * x[0]])

    def observation(x, phi, u_t):
        return np.array([x[0] + phi[0]])

    return StateModel(
        evolution=evolution,
        observation=observation,
        family="gaussian",
        priors=Priors(GaussianPrior([0.8], [0.2], names=["persistence"]), GaussianPrior([0.0], [1.0], names=["offset"])),
        initial_state=[0.0],
        initial_state_covariance=[1.0],
        process_covariance=[0.10],
        observation_covariance=[0.25],
        state_names=["hidden_state"],
        name="stochastic continuous state model",
    )
